name: netflix
description: Netflix portifolio com a base de Clean Architecture.

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  dio: 4.0.6
  bloc: 8.0.3
  equatable: 2.0.3
  get_it: 7.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
flutter:
  uses-material-design: true
